import sys

def logger(log_print):
	print(f"{log_print}")

def turing_state_machine_01():
	input_instructions = {}
	input_instructions.update({"A60": "790D"})
	input_instructions.update({"B60": "770D"})
	input_instructions.update({"C60": "651A"})
	input_instructions.update({"D60": "6D1A"})
	input_instructions.update({"E60": "6D1D"})
	input_instructions.update({"A61": "680A"})
	input_instructions.update({"B61": "601D"})
	input_instructions.update({"C61": "681E"})
	input_instructions.update({"D61": "651B"})
	input_instructions.update({"E61": "621D"})
	input_instructions.update({"A62": "600A"})
	input_instructions.update({"B62": "790C"})
	input_instructions.update({"C62": "641B"})
	input_instructions.update({"D62": "6A1E"})
	input_instructions.update({"E62": "740E"})
	input_instructions.update({"A63": "6A0B"})
	input_instructions.update({"B63": "690C"})
	input_instructions.update({"C63": "791A"})
	input_instructions.update({"D63": "710A"})
	input_instructions.update({"E63": "6A1E"})
	input_instructions.update({"A64": "771C"})
	input_instructions.update({"B64": "791C"})
	input_instructions.update({"C64": "621D"})
	input_instructions.update({"D64": "601D"})
	input_instructions.update({"E64": "781A"})
	input_instructions.update({"A65": "650B"})
	input_instructions.update({"B65": "6A0A"})
	input_instructions.update({"C65": "690B"})
	input_instructions.update({"D65": "611D"})
	input_instructions.update({"E65": "751C"})
	input_instructions.update({"A66": "630C"})
	input_instructions.update({"B66": "6C1A"})
	input_instructions.update({"C66": "651C"})
	input_instructions.update({"D66": "781A"})
	input_instructions.update({"E66": "6C1B"})
	input_instructions.update({"A67": "670B"})
	input_instructions.update({"B67": "731C"})
	input_instructions.update({"C67": "790E"})
	input_instructions.update({"D67": "6D1B"})
	input_instructions.update({"E67": "7E0B"})
	input_instructions.update({"A68": "621E"})
	input_instructions.update({"B68": "610E"})
	input_instructions.update({"C68": "721E"})
	input_instructions.update({"D68": "000H"})
	input_instructions.update({"E68": "670A"})
	input_instructions.update({"A69": "7D1C"})
	input_instructions.update({"B69": "7D1B"})
	input_instructions.update({"C69": "610E"})
	input_instructions.update({"D69": "721C"})
	input_instructions.update({"E69": "7E0E"})
	input_instructions.update({"A6A": "621A"})
	input_instructions.update({"B6A": "791B"})
	input_instructions.update({"C6A": "671E"})
	input_instructions.update({"D6A": "6D1C"})
	input_instructions.update({"E6A": "740E"})
	input_instructions.update({"A6B": "600E"})
	input_instructions.update({"B6B": "600A"})
	input_instructions.update({"C6B": "6C0A"})
	input_instructions.update({"D6B": "6C1A"})
	input_instructions.update({"E6B": "731E"})
	input_instructions.update({"A6C": "751B"})
	input_instructions.update({"B6C": "620E"})
	input_instructions.update({"C6C": "7A0E"})
	input_instructions.update({"D6C": "790D"})
	input_instructions.update({"E6C": "6C0E"})
	input_instructions.update({"A6D": "7D1B"})
	input_instructions.update({"B6D": "7C1A"})
	input_instructions.update({"C6D": "6E1C"})
	input_instructions.update({"D6D": "601B"})
	input_instructions.update({"E6D": "6D0D"})
	input_instructions.update({"A6E": "661A"})
	input_instructions.update({"B6E": "640A"})
	input_instructions.update({"C6E": "6A1B"})
	input_instructions.update({"D6E": "661B"})
	input_instructions.update({"E6E": "6E1D"})
	input_instructions.update({"A70": "7A0A"})
	input_instructions.update({"B70": "711C"})
	input_instructions.update({"C70": "640E"})
	input_instructions.update({"D70": "7A1C"})
	input_instructions.update({"E70": "601E"})
	input_instructions.update({"A71": "6D0A"})
	input_instructions.update({"B71": "771B"})
	input_instructions.update({"C71": "711C"})
	input_instructions.update({"D71": "751A"})
	input_instructions.update({"E71": "640E"})
	input_instructions.update({"A72": "690D"})
	input_instructions.update({"B72": "730B"})
	input_instructions.update({"C72": "651A"})
	input_instructions.update({"D72": "690C"})
	input_instructions.update({"E72": "690D"})
	input_instructions.update({"A73": "790D"})
	input_instructions.update({"B73": "780C"})
	input_instructions.update({"C73": "750D"})
	input_instructions.update({"D73": "611B"})
	input_instructions.update({"E73": "790A"})
	input_instructions.update({"A74": "7C1E"})
	input_instructions.update({"B74": "771A"})
	input_instructions.update({"C74": "671D"})
	input_instructions.update({"D74": "6B0B"})
	input_instructions.update({"E74": "791E"})
	input_instructions.update({"A75": "601C"})
	input_instructions.update({"B75": "730E"})
	input_instructions.update({"C75": "7C1C"})
	input_instructions.update({"D75": "671A"})
	input_instructions.update({"E75": "641B"})
	input_instructions.update({"A76": "7D0A"})
	input_instructions.update({"B76": "7D0A"})
	input_instructions.update({"C76": "690C"})
	input_instructions.update({"D76": "6E0E"})
	input_instructions.update({"E76": "611A"})
	input_instructions.update({"A77": "620B"})
	input_instructions.update({"B77": "6C0E"})
	input_instructions.update({"C77": "630C"})
	input_instructions.update({"D77": "611E"})
	input_instructions.update({"E77": "711C"})
	input_instructions.update({"A78": "791E"})
	input_instructions.update({"B78": "671E"})
	input_instructions.update({"C78": "710E"})
	input_instructions.update({"D78": "6D0D"})
	input_instructions.update({"E78": "7B1E"})
	input_instructions.update({"A79": "7D0A"})
	input_instructions.update({"B79": "670D"})
	input_instructions.update({"C79": "7C0B"})
	input_instructions.update({"D79": "6E0A"})
	input_instructions.update({"E79": "660E"})
	input_instructions.update({"A7A": "6D1A"})
	input_instructions.update({"B7A": "711A"})
	input_instructions.update({"C7A": "710C"})
	input_instructions.update({"D7A": "730D"})
	input_instructions.update({"E7A": "631C"})
	input_instructions.update({"A7B": "6A1A"})
	input_instructions.update({"B7B": "770A"})
	input_instructions.update({"C7B": "600E"})
	input_instructions.update({"D7B": "680B"})
	input_instructions.update({"E7B": "690A"})
	input_instructions.update({"A7C": "611E"})
	input_instructions.update({"B7C": "7A0A"})
	input_instructions.update({"C7C": "710E"})
	input_instructions.update({"D7C": "6D1B"})
	input_instructions.update({"E7C": "630D"})
	input_instructions.update({"A7D": "660D"})
	input_instructions.update({"B7D": "7B0A"})
	input_instructions.update({"C7D": "721E"})
	input_instructions.update({"D7D": "671E"})
	input_instructions.update({"E7D": "7D0B"})
	input_instructions.update({"A7E": "761D"})
	input_instructions.update({"B7E": "7A0D"})
	input_instructions.update({"C7E": "751B"})
	input_instructions.update({"D7E": "761A"})
	input_instructions.update({"E7E": "670B"})
	logger(f"{input_instructions}")
	loop_count = 0
	position = 0
	dict = { 0: 60 }
	instruction = "600A"
	while "H" != instruction[3:]:
		card =  str(instruction[3:]) + str((dict.get(int(position), 60)))
		instruction = input_instructions[card]
		dict[position] = instruction[0:2]
		position = int(position) + int(instruction[2:3])
		if int(instruction[2:3]) == 0:
			if int(position) == 0:
				new_dict = {}
				for k, v in dict.items():
					new_dict[int(k)+1] = v
				dict = { 0: 60 }
				dict.update(new_dict)
			else:
				position -= 1
		loop_count += 1
		#move the below in/out of loop for when to print output
		arr = str(list(dict.values()))
		arr = arr.replace(",", "").replace("\'", "").replace(" ", "").replace("[", "").replace("]", "")
		bytes_object = bytes.fromhex(arr)
		ascii_string = bytes_object.decode("ASCII")
		logger(f"{ascii_string}")

def main():
	import time
	start_time = time.time()
	logger(f"## start:{start_time}")
	turing_state_machine_01()
	end_time = time.time()
	logger(f"##   end:{end_time}")
	total_time = end_time - start_time
	logger(f"## total:{total_time}")

main()
exit(0)
